kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: elk
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30601
        hostPort: 5601
        protocol: TCP
      - containerPort: 30080
        hostPort: 8082
        protocol: TCP
