apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: logging
data:
  elasticsearch.yml: |
    cluster.name: elk-cluster
    node.name: elasticsearch-0
    discovery.type: single-node
    network.host: 0.0.0.0
    xpack.security.enabled: false
    xpack.license.self_generated.type: basic
    xpack.ml.enabled: false
