input {
  file {
    path => "/data/Air_Quality.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    mode => "read"
  }
}

filter {
  csv {
    separator => ","
    columns => [
      "unique_id", "indicator_id", "name", "measure", "measure_info",
      "geo_type_name", "geo_join_id", "geo_place_name", "time_period",
      "start_date", "data_value", "extra"
    ]
  }

  # Supprimer la ligne d'en-tête
  if [unique_id] == "Unique ID" {
    drop {}
  }

  # Convertir la date CSV → @timestamp
  date {
    match => ["start_date", "MM/dd/yyyy"]
    target => "@timestamp"
  }

  mutate {
    convert => {
      "unique_id"    => "integer"
      "indicator_id" => "integer"
      "data_value"   => "float"
    }
    remove_field => ["message", "extra", "@version", "log", "event", "start_date", "host"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "air-quality-%{+YYYY}"
    document_id => "%{unique_id}"
    action => "index"
  }
}
